name: Issue

on:
  issues:
    types: [opened, labeled]
jobs:
  issueHandler:
    name: IssueHandler
    if: github.event.action == 'opened' || (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'verify'))
    permissions:
      contents: read # write required for comment?
      issues: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: IssueHandler
        uses: ScoopInstaller/GithubActions@main
        env:
          SCOOP_BRANCH: develop
