name: PR

on:
  pull_request:
    types: [opened] # dangerous-triggers, see zizmor.yml
  issue_comment:
    types: [created]
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    permissions:
      contents: read
      pull-requests: write # required for PR
    if: >-
      ( github.event_name == 'pull_request' ||
        (
          github.event_name == 'issue_comment'
          github.event.issue.pull_request &&
          startsWith(github.event.comment.body, '/verify')
         )
       ) &&
       (
         github.actor == 'Vinfall' ||
         github.actor == 'github-actions[bot]'
       )
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - name: PullRequestHandler
        uses: ScoopInstaller/GithubActions@main
        env:
          SCOOP_BRANCH: develop
