name: PR

on:
  pull_request:
    types: [opened] # dangerous-triggers, see zizmor.yml
  issue_comment:
    types: [created]
jobs:
  pullRequestHandler:
    name: Pull Request Handler
    permissions:
      contents: read
      pull-requests: write # required for PR
    if: >-
      ( github.event_name == 'pull_request' ||
        (
          github.event_name == 'issue_comment' &&
          github.event.issue.pull_request &&
          startsWith(github.event.comment.body, '/verify')
        )
      ) &&
      (
        github.actor == 'Vinfall' ||
        github.event.pull_request.user.login == 'dependabot[bot]'
      )
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: PullRequestHandler
        uses: ScoopInstaller/GithubActions@5bceeda181721d9d10a18fdcc3ddca6f33467ae6 # v3.0.0
        env:
          SCOOP_BRANCH: develop
