name: Test

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  test_powershell:
    name: WindowsPowerShell
    permissions:
      contents: read
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 2
          path: my_bucket
      - name: Checkout Scoop
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          repository: ScoopInstaller/Scoop
          path: scoop_core
      - name: Init Test Suite
        uses: potatoqualitee/psmodulecache@main
        with:
          modules-to-cache: BuildHelpers
          shell: powershell
      - name: Test Bucket
        shell: powershell
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
          .\my_bucket\bin\test.ps1
