name: Update

on:
  workflow_dispatch:
  schedule:
    # run every 8 hours
    - cron: "20 */8 * * *"
jobs:
  update:
    name: update
    runs-on: windows-latest
    permissions:
      contents: write # required to update
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: true # required to update
      - uses: ScoopInstaller/GithubActions@main
        env:
          SKIP_UPDATED: 1
          SCOOP_BRANCH: develop
